<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
    <title>Manual Tests V2</title>

    <script
      src="/dist/packages/lit-node-client-vanilla/lit-node-client.js"
    ></script>
    <script
      src="https://cdn.ethers.io/lib/ethers-5.2.umd.min.js"
      type="application/javascript"
    ></script>
    <script>

      const LitJsSdk = LitJsSdk_litNodeClient;

      const litNodeClient = new LitNodeClient({litNetwork: 'cayenne'});
      litNodeClient.connect();

      //var authSig = JSON.parse("{\"sig\":\"0x18a173d68d2f78cc5c13da0dfe36eec2a293285bee6d42547b9577bf26cdc985660ed3dddc4e75d422366cac07e8a9fc77669b10373bef9c7b8e4280252dfddf1b\",\"derivedVia\":\"web3.eth.personal.sign\",\"signedMessage\":\"I am creating an account to use LITs at 2021-08-04T20:14:04.918Z\",\"address\":\"0xdbd360f30097fb6d938dcc8b7b62854b36160b45\"}")

      var randomPath = () =>
        "/" +
        Math.random().toString(36).substring(2, 15) +
        Math.random().toString(36).substring(2, 15);
      var testProvisoningAndSigning = async ({
        evmContractConditions,
        testName,
      }) => {
        document.getElementById("status").innerText = `Testing ${testName}...`;
        // document.getElementById(
        //   "humanized"
        // ).innerText = `Humanized: ${await LitJsSdk.humanizeAccessControlConditions(
        //   { evmContractConditions }
        // )}`;

        var authSig = await LitJsSdk.checkAndSignAuthMessage({ chain });

        let jwt = await litNodeClient.getSignedToken({
          evmContractConditions,
          chain,
          authSig,
        });
        console.log("jwt", jwt);

        // uncomment this to break the jwt, to test an invalid jwt
        // jwt = jwt.replace(/.$/, "3");

        const { verified, header, payload } = LitJsSdk.verifyJwt({ jwt, publicKey: litNodeClient.networkPubKey });
        console.log("verified", verified);
        console.log("header", header);
        console.log("payload", payload);

        if (jwt && verified) {
          document.getElementById("status").innerText = `${testName}: Success`;
        } else {
          document.getElementById("status").innerText = `${testName}: Failure`;
        }
      };

      var testProvisoningEncryptingAndDecrypting = async ({
        evmContractConditions,
        chain,
        doNotStoreCondition = false,
        testName,
      }) => {
        document.getElementById("status").innerText = `Testing ${testName}...`;
        const authSig = await LitJsSdk.checkAndSignAuthMessage({
          chain,
        });

        // document.getElementById(
        //   "humanized"
        // ).innerText = `Humanized: ${await LitJsSdk.humanizeAccessControlConditions(
        //   { accessControlConditions }
        // )}`;

        const { ciphertext, dataToEncryptHash } = await LitJsSdk.zipAndEncryptString(
          {
            dataToEncrypt: 'this is a secret message',
            evmContractConditions,
            chain,
            authSig,
          },
          litNodeClient,
        );

        const decryptedFiles = await LitJsSdk.decryptToZip(
          {
            evmContractConditions,
            chain,
            authSig,
            ciphertext,
            dataToEncryptHash,
          },
          litNodeClient,
        );

        const decryptedString = await decryptedFiles["string.txt"].async(
          "text"
        );
        console.log("decrypted string", decryptedString);

        document.getElementById(
          "status"
        ).innerText = `${testName}: Success.  Decrypted string is: ${decryptedString}`;
      };

      // Actual tests are below here
      var MissingChain = async () => {
        var evmContractConditions = [
          {
            contractAddress: "0x7C7757a9675f06F3BE4618bB68732c4aB25D2e88",
            functionName: "balanceOf",
            functionParams: [":userAddress", "8"],
            functionAbi: {
              type: "function",
              stateMutability: "view",
              outputs: [
                {
                  type: "uint256",
                  name: "",
                  internalType: "uint256",
                },
              ],
              name: "balanceOf",
              inputs: [
                {
                  type: "address",
                  name: "account",
                  internalType: "address",
                },
                {
                  type: "uint256",
                  name: "id",
                  internalType: "uint256",
                },
              ],
            },
            // chain,
            returnValueTest: {
              key: "",
              comparator: ">",
              value: "0",
            },
          },
        ];
        try {
          await testProvisoningAndSigning({
            evmContractConditions,
            testName: "MissingChain",
          });
          document.getElementById(
            "status"
          ).innerText = `MissingChain: Failed.  It should have thrown an exception but it didn't.`;
        } catch (e) {
          console.log("Error on MissingChain", e);
          document.getElementById(
            "status"
          ).innerText = `MissingChain: Success.  Failed with error ${JSON.stringify(
            e,
            null,
            2
          )}`;
        }
      };

      var Unauthorized = async () => {
        var evmContractConditions = [
          {
            contractAddress: "0x7C7757a9675f06F3BE4618bB68732c4aB25D2e88",
            functionName: "balanceOf",
            functionParams: [":userAddress", "8"],
            functionAbi: {
              type: "function",
              stateMutability: "view",
              outputs: [
                {
                  type: "uint256",
                  name: "",
                  internalType: "uint256",
                },
              ],
              name: "balanceOf",
              inputs: [
                {
                  type: "address",
                  name: "account",
                  internalType: "address",
                },
                {
                  type: "uint256",
                  name: "id",
                  internalType: "uint256",
                },
              ],
            },
            chain,
            returnValueTest: {
              key: "",
              comparator: ">",
              value: "10000",
            },
          },
        ];

        try {
          await testProvisoningAndSigning({
            evmContractConditions,
            testName: "Unauthorized",
          });
          document.getElementById(
            "status"
          ).innerText = `Unauthorized: Failed.  It should have thrown an exception but it didn't.`;
        } catch (e) {
          console.log("Error on Unauthorized", e);
          document.getElementById(
            "status"
          ).innerText = `Unauthorized: Success.  Failed with error ${JSON.stringify(
            e,
            null,
            2
          )}`;
        }
      };

      var MissingChainEncryptDecrypt = async () => {
        var evmContractConditions = [
          {
            contractAddress: "0x7C7757a9675f06F3BE4618bB68732c4aB25D2e88",
            functionName: "balanceOf",
            functionParams: [":userAddress", "8"],
            functionAbi: {
              type: "function",
              stateMutability: "view",
              outputs: [
                {
                  type: "uint256",
                  name: "",
                  internalType: "uint256",
                },
              ],
              name: "balanceOf",
              inputs: [
                {
                  type: "address",
                  name: "account",
                  internalType: "address",
                },
                {
                  type: "uint256",
                  name: "id",
                  internalType: "uint256",
                },
              ],
            },
            // chain,
            returnValueTest: {
              key: "",
              comparator: ">",
              value: "0",
            },
          },
        ];
        try {
          await testProvisoningEncryptingAndDecrypting({
            evmContractConditions,
            testName: "MissingChainEncryptDecrypt",
          });
          document.getElementById(
            "status"
          ).innerText = `MissingChainEncryptDecrypt: Failed.  It should have thrown an exception but it didn't.`;
        } catch (e) {
          console.log("Error on MissingChainEncryptDecrypt", e);
          document.getElementById(
            "status"
          ).innerText = `MissingChainEncryptDecrypt: Success.  Failed with error ${JSON.stringify(
            e,
            null,
            2
          )}`;
        }
      };

      var UnauthorizedEncryptDecrypt = async () => {
        var evmContractConditions = [
          {
            contractAddress: "0x7C7757a9675f06F3BE4618bB68732c4aB25D2e88",
            functionName: "balanceOf",
            functionParams: [":userAddress", "8"],
            functionAbi: {
              type: "function",
              stateMutability: "view",
              outputs: [
                {
                  type: "uint256",
                  name: "",
                  internalType: "uint256",
                },
              ],
              name: "balanceOf",
              inputs: [
                {
                  type: "address",
                  name: "account",
                  internalType: "address",
                },
                {
                  type: "uint256",
                  name: "id",
                  internalType: "uint256",
                },
              ],
            },
            chain: "polygon",
            returnValueTest: {
              key: "",
              comparator: ">",
              value: "10000",
            },
          },
        ];

        try {
          await testProvisoningEncryptingAndDecrypting({
            evmContractConditions,
            chain: "polygon",
            testName: "UnauthorizedEncryptDecrypt",
          });
          document.getElementById(
            "status"
          ).innerText = `UnauthorizedEncryptDecrypt: Failed.  It should have thrown an exception but it didn't.`;
        } catch (e) {
          console.log("Error on UnauthorizedEncryptDecrypt", e);
          document.getElementById(
            "status"
          ).innerText = `UnauthorizedEncryptDecrypt: Success.  Failed with error ${JSON.stringify(
            e,
            null,
            2
          )}`;
        }
      };

      var logout = async () => {
        const testName = "Logout";
        document.getElementById("status").innerText = `Testing ${testName}...`;

        LitJsSdk.disconnectWeb3();

        document.getElementById(
          "status"
        ).innerText = `${testName}: Success - Logged out`;
      };

      document.addEventListener(
        "lit-ready",
        function (e) {
          console.log("LIT network is ready");
          document.getElementById("networkStatus").innerText =
            "Success!  Connected to Lit Protocol Network";
        },
        false
      );

      function isNodeStorageError(errorCode) {
        return errorCode === 'storage_error' || errorCode === 'NodeStorageError';
      }
    </script>
  </head>

  <body>
    <h1>Manual tests</h1>
    <br />
    <br />
    <div id="networkStatus">Connecting to Lit Protocol Network...</div>
    <br />
    <br />
    <button onclick="MissingChain()">MissingChain</button>
    <br />
    <br />
    <button onclick="Unauthorized()">Unauthorized</button>
    <br />
    <br />

    <button onclick="MissingChainEncryptDecrypt()">
      MissingChainEncryptDecrypt
    </button>
    <br />
    <br />
    <button onclick="UnauthorizedEncryptDecrypt()">
      UnauthorizedEncryptDecrypt
    </button>
    <br />
    <br />

    <button onclick="logout()">Logout</button>
    <br />
    <br />
    <h2 id="status"></h2>
    <br />
    <p id="humanized"></p>
  </body>
</html>
